- name: "MYSQL query"
  hosts: localhost
  become: true
  gather_facts: no
  vars:
    username: "root"
    ansible_python_interpreter: /usr/bin/python3
    database: "backend"  # Specify the database
  tasks:
    - name: "Connect to MYSQL and USE {{ database }}"
      community.mysql.mysql_query:
        login_user: "{{ username }}"
        login_host: localhost
        login_port: 3306
        login_db: "{{ database }}"
        query: "SELECT 1;"
      register: mysql_connection_result
    
    - name: "INSERT values into DB {{ database }}"
      community.mysql.mysql_query:
        query: |
          INSERT INTO {{ database }} (name, bcit_id)
          VALUES ('John Doe', 'BCIT123'),
                 ('Alice Smith', 'BCIT456');
      register: insert_output
    
    - name: "Debug INSERT output"
      debug:
        msg: "{{ insert_output }}"
    
    - name: "SELECT all from table {{ database }}"
      community.mysql.mysql_query:
        query: "SELECT * FROM {{ database }}"
      register: select_all_output

    - name: "Debug SELECT all output"
      debug:
        msg: "{{ select_all_output }}"